### ISSUE TITLE
Gamewisp Sub Emotes

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/MixrElixr#22]
Gamewisp has sub emotes. If you subscribe to certain tiers for a user you can use these emotes.

Had requests to put this into Elixr, but I'm not sure exactly how the API works or anything. For example, not sure how it would match up a mixir username to a gamewisp username to determine if they should be able to use the emote.

Research needed.

**Comment by ebiggz** [comment]
Did some research on this.
I dont see anything offhand in their API docs that give access to emotes
https://gamewisp.readme.io/docs/introduction-1

But it seems like its possible somehow according to this document
https://gamewisp.zendesk.com/hc/en-us/articles/115004490927-How-to-Use-GameWisp-Emotes

In that article, there is a specific "Do emotes work on Mixer question?" that says if anyone is developing an extension to reach out and email them. So I will do that and see what info they can provide.

**Comment by ebiggz** [comment]
Got a reply from Eli Hooten from GameWisp. It sounds like they need to make some backend changes before we can implement sub badges and emotes in a straightforward manor. They are interested in making those changes so we can implement this feature though, so they are going keep in touch and if/when they find the time, we can move forward on this.

**Comment by ebiggz** [comment]
RIP GameWisp.
