### ISSUE TITLE
[Bug] Timestamps Disapearing

### ISSUE THREAD

**Issue by MAPReiff** [crowbartools/MixrElixr#32]
So I have encountered an issue with the timestamp feature. It seems whenever the standard Mixer timestamp is generated and put into chat, the ones made by the plugin disappear for the 3rd previous section (bottom 2 still have them, ones above lose them).
Having this issue on plugin version 1.2, chrome version 62.0.3202.75 on Mac OS.

<img width="381" alt="fcgxhvjkl" src="https://user-images.githubusercontent.com/7242589/32526348-dd03d6a4-c3f6-11e7-94b9-bd1253602776.png">

(Sorry for the title change, hit enter by mistake.)

**Comment by Buttercup451** [comment]
Hmmm, that's very weird. I'll do some testing this week and see if I can't help pin it down. Not sure why it would do that

**Comment by Firebottle** [comment]
Are you sure it's actually erasing them? The feature will only start putting in timestamps for messages after the latest "real" timestamp when the page is loaded. It does this because we can't timestamp things that happened before you go to the channel.

**Comment by MAPReiff** [comment]
I was on the page the entire time, they were just disappearing as mixer did its own auto time stamp thing. I'll see if the issue persists tonight.

**Comment by Firebottle** [comment]
Awesome, thanks! I know ebiggz and I tried to reproduce the other day and couldn't get it to happen. I'll keep trying!

**Comment by MAPReiff** [comment]
I have been unable to reproduce it. Maybe it was just a one time fluke.
