### ISSUE TITLE
Firefox Add-On "Page not Found"

### ISSUE THREAD

**Issue by ghost** [crowbartools/MixrElixr#46]
The README link goes to a page that no longer exists, and I cannot seem to find the add-on when searching the Firefox add-on site.

Is there another way to get this working? Thanks!

**Comment by ebiggz** [comment]
Firebot has removed us from their extension gallery page and has required we make changes before we can re add it. Unfortunately these changes will largely require us to redo most of the app, so until one of us has more time, we will only be available on Chrome.
