### ISSUE TITLE
[Feature Request] Custom Channel Emotes for everyone

### ISSUE THREAD

**Issue by D3thw0lf** [crowbartools/MixrElixr#49]
I would ❤️ to see something similar to BTTV or FrankerFaceZ for mixer.com 👍 (this would also be a great addition, I guess, for everyone without being partnered and ofc you could monetize it a bit like the named extensions)

**Comment by Firebottle** [comment]
FYI, we've started looking into this and think we may have found a possible solution. I'll try to keep you guys updated as it progresses.

**Comment by ebiggz** [comment]
Heads up this feature has been implemented in 2.0!
