### ISSUE TITLE
[Suggestion] Javascript Notifications or something else for streamers going live?

### ISSUE THREAD

**Issue by Setarii** [crowbartools/MixrElixr#59]
So I ran into an issue (And FierySama did as well) with the website that texts you when a streamer goes live. I usually have my computer on and my chrome web browser open as well, and thought MixrElixr being able to push notifications would be nice. Fiery also mentioned that Mixer can push its own notifications but I've found them to be unreliable as to when a streamer goes live, so I thought maybe you guys could create a more reliable notification push.

I would not look down on a text message option as well if that was an option too.

Also still waiting on that puss peepers option

**Comment by ebiggz** [comment]
This has been implemented in 2.0. Thanks @Setarii !
