### ISSUE TITLE
ChannelOne missing

### ISSUE THREAD

**Issue by antisocialian** [crowbartools/MixrElixr#60]
For some reason ChannelOne doesn't show even tho i have followed their channel. It seems to be hidden whether it has been set as a favourite or not.

Using Chrome version, not sure if that matters or not...

**Comment by Firebottle** [comment]
Hi! Channels will only show if they're actively broadcasting. If they're just hosting someone it wont show.

**Comment by antisocialian** [comment]
:facepalm
