### ISSUE TITLE
Theater Mode Bug

### ISSUE THREAD

**Issue by JPili** [crowbartools/MixrElixr#69]
If the browser window is dragged to the left or right so it only takes up half the screen, it causes theater mode to not work properly.

Whenever I enable theater mode while the browser window is only taking up half the screen, it causes the video player to get pushed to the top of the screen and become super small. A workaround to fix the size is to disable and then enable "Larger Video Feed" in the settings. But even then, the video player is still pushed up to the top of the screen and isn't centered. 

Please fix soon. The lack of a proper theater mode is the reason I don't like watching Mixer channels that much.

I'm using Firefox and my screen resolution is 2560x1440.

**Comment by Firebottle** [comment]
Just to be sure I understand, youre resizing the browser window right? Is
the site in the mobile view when this happens? At certain sizes on desktop
mixer will go into mobile view. Check the URL to see.

**Comment by ebiggz** [comment]
Hi @JPili , the latest version released today (v2.4.0) should resolve the theater mode issues you detailed here. Thanks for the report.
