### ISSUE TITLE
Theater Button Missing

### ISSUE THREAD

**Issue by Tsunami2069** [crowbartools/MixrElixr#71]
So for quite a while that the theater button has been AWOL.

The streams go into theater mode thanks to the auto-theater mode which has been working beautifuly (thanks for that)... but if, for whatever reason, i have to get out of theater mode (check something on teh channel, use a sticker or something, mixplay, etc.), i have no other way of going back to theater mode except refreshing the page to trigger the auto-theater again.

![Snip1](https://user-images.githubusercontent.com/14236716/65439972-ee026e80-de1f-11e9-94aa-fafad6013a95.jpg)

I have tried disabling all of my other extentions to try to see if it was a conflict but the result is still the same.

I'm using Chrome at the most recent version (77.0.3865.90).

Thanks.

**Comment by ebiggz** [comment]
This should be fixed in v2.3.2 that was just released. Thanks for the report!
