### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by Elite911** [crowbartools/MixrElixr#75]
Hello,

Just wondering do you think you'd ever make the extension on Edge as well or would it be just Firefox and Chrome?

**Comment by brumoen** [comment]
We already support Edge(Chromium Edge). The "original" Microsoft Edge is discontinued and will be swapped out with the Chromium based one when it's done so we won't be making an extension for that one.
If you don't already have it, the Chromium based one, you can get it at the [Microsoft Edge Insider website](www.microsoftedgeinsider.com)

We already support Chromium based browsers(Vivaldi, Brave, Opera, Edge and so on) so to install it on Chromium Edge:
Click the three dots top right corner to open the menu: Go to Settings -> Extensions -> Turn on "Allow Extensions from other stores" -> Then go to [MixrElixr on the Chrome Webstore](https://chrome.google.com/webstore/detail/mixrelixr/mmfbdcekojokeeonagpnlpoklelkcjon?hl=en) and click on Install.
