### ISSUE TITLE
[Bug] Elixr doesn't detect that i'm logged into Mixer

### ISSUE THREAD

**Issue by DevilzAvacado** [crowbartools/MixrElixr#86]
On the "Live Now" tab in the extension it tells me "To see who follow, go to Mixer.com and log in. " even though i'm logged in. I tried logging out and then logging back in to see if that would work and it didn't. 
![image](https://user-images.githubusercontent.com/11524516/69816577-981bbf80-11f0-11ea-9ed1-6b8461239467.png)

**Comment by SReject** [comment]
Could you give us system details:

* Operating System
* Browser
* Elixr Version

**Comment by DevilzAvacado** [comment]
Windows 10
Firefox
2.10.1

**Comment by CowboyTechTV** [comment]
Same with me.

I'm using Windows 10
Opera GX/Google Chrome
Version 2.10.1

**Comment by LastMageTV** [comment]
@DevilzAvacado @CowboyTechTV just in case you haven't fixed this, simply re-logging on mixer will fix the issue. We will take a closer look into the issue.
