### ISSUE TITLE
[Bug] Theater Mode wrongfuly positioned downards - playback controls offscreen

### ISSUE THREAD

**Issue by Tsunami2069** [crowbartools/MixrElixr#90]
**Describe the bug**
The theater mode appears mode further down then it should, with a blank bar on top.
The bar has the same as the normal mixer top bar. Its like the video doesn't reposition to the top or the bar isn't hidden.
This also makes the video controls (play, volume, etc) to be offscreen and inaccessible.

**To Reproduce**
1. Open a stream with Theater Mode. Or turn on theater mode. 

**Expected behavior**
The Icon and title and host button, mixplay, etc is on top and the video fits. The video playback controls (volume, etc.) are also accessible.

**Screenshots**
![Snip1](https://user-images.githubusercontent.com/14236716/72381641-a6298f00-370f-11ea-9c89-e5dad394f5c9.jpg)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome (79.0.3945.117 (Official Build) (64-bit))
 - MixrElixr Version: 2.10.1

**Comment by ebiggz** [comment]
@Tsunami2069 Thanks for the report! I've got a working fix and am uploading a new version of the extension to the Chrome/Firefox stores. It should propagate out within the hour.

**Comment by ebiggz** [comment]
Released in v2.10.2

**Comment by Tsunami2069** [comment]
Much appreciated :)
Love the extension, keep up the good work.
