### ISSUE TITLE
Crowbartools WebSite is down, no emotes

### ISSUE THREAD

**Issue by sushihangover** [crowbartools/MixrElixr#93]
The crowbartools.com is returning 404s for the entire site.

**Comment by brumoen** [comment]
Please keep an eye on this Tweet: https://twitter.com/MixrElixr/status/1221120925166456833

We are aware and we will post an update on Twitter as soon as we have a solution.

**Comment by sushihangover** [comment]
@brumoen Thank you very much for the quick update.

-Robert
