### ISSUE TITLE
Not available from the Firefox store

### ISSUE THREAD

**Issue by sushihangover** [crowbartools/MixrElixr#99]
The mixrelixr addon is not available anymore. Did Crowbar pull it, or did Mozillia? 

From https://addons.mozilla.org/en-US/firefox/addon/mixrelixr/

> If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:
> 
> The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
> Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

TIA, -Robert

**Comment by ebiggz** [comment]
Hi @sushihangover! Sorry for the inconvenience. Mozilla pulled it. We are working with them and uploaded a new build earlier today. We aren't sure when it will be back in the store. Could be anything from a couple hours to a couple days.

**Comment by sushihangover** [comment]
Thanks for the amazingly quick reply.

Had multiple people asking on Shroud's stream, so it is missed 😜 (we use MixrElixr ALOT on that channel. Thanks again.

**Comment by ebiggz** [comment]
@sushihangover Sure thing. As of a few hours ago, Elixr was added back to the Firefox add-on gallery. 🎉 Thanks for stopping by to let us know.
